import { generateUniqueId } from "./generateUniqueId";

export const userData = [
  {
    id: generateUniqueId,
    name: "Abiodun Olawale Solomom",
    address: "12b Emmanuel High Street Along Surface Road",
    bank: "Sterling Bank PLC",
    createdAt: "A Day Ago", //It can be represent as UTC time and date
    status: "Unassigned",
  },
  {
    id: generateUniqueId,
    name: "John Obinna",
    address: "1c Timothy road, off isolo way",
    bank: "Eco Bank PLC",
    createdAt: "1 Week Ago",
    status: "Completed",
  },
  {
    id: generateUniqueId,
    name: "Chukwudi Joshua",
    address: "34 off lekki phase one, tension road",
    bank: "First Bank PLC",
    createdAt: "2 week Ago",
    status: "Assigned",
  },
  {
    id: generateUniqueId,
    name: "Abiodun Olawale Solomom",
    address: "12b Emmanuel High Street Along Surface Road",
    bank: "Sterling Bank PLC",
    createdAt: "A Day Ago",
    status: "Unassigned",
  },
  {
    id: generateUniqueId,
    name: "John Obinna",
    address: "1c Timothy road, off isolo way",
    bank: "Eco Bank PLC",
    createdAt: "1 Week Ago",
    status: "Completed",
  },
  {
    id: generateUniqueId,
    name: "Chukwudi Joshua",
    address: "34 off lekki phase one, tension road",
    bank: "First Bank PLC",
    createdAt: "2 week Ago",
    status: "Assigned",
  },
  {
    id: generateUniqueId,
    name: "Abiodun Olawale Solomom",
    address: "12b Emmanuel High Street Along Surface Road",
    bank: "Sterling Bank PLC",
    createdAt: "A Day Ago",
    status: "Unassigned",
  },
  {
    id: generateUniqueId,
    name: "John Obinna",
    address: "1c Timothy road, off isolo way",
    bank: "Eco Bank PLC",
    createdAt: "1 Week Ago",
    status: "Completed",
  },
  {
    id: generateUniqueId,
    name: "Chukwudi Joshua",
    address: "34 off lekki phase one, tension road",
    bank: "First Bank PLC",
    createdAt: "2 week Ago",
    status: "Assigned",
  },
  {
    id: generateUniqueId,
    name: "Abiodun Olawale Solomom",
    address: "12b Emmanuel High Street Along Surface Road",
    bank: "Sterling Bank PLC",
    createdAt: "A Day Ago",
    status: "Unassigned",
  },
  {
    id: generateUniqueId,
    name: "John Obinna",
    address: "1c Timothy road, off isolo way",
    bank: "Eco Bank PLC",
    createdAt: "1 Week Ago",
    status: "Completed",
  },
  {
    id: generateUniqueId,
    name: "Chukwudi Joshua",
    address: "34 off lekki phase one, tension road",
    bank: "First Bank PLC",
    createdAt: "2 week Ago",
    status: "Assigned",
  },
  {
    id: generateUniqueId,
    name: "Abiodun Olawale Solomom",
    address: "12b Emmanuel High Street Along Surface Road",
    bank: "Sterling Bank PLC",
    createdAt: "A Day Ago",
    status: "Unassigned",
  },
  {
    id: generateUniqueId,
    name: "John Obinna",
    address: "1c Timothy road, off isolo way",
    bank: "Eco Bank PLC",
    createdAt: "1 Week Ago",
    status: "Completed",
  },
  {
    id: generateUniqueId,
    name: "Chukwudi Joshua",
    address: "34 off lekki phase one, tension road",
    bank: "First Bank PLC",
    createdAt: "2 week Ago",
    status: "Assigned",
  },
  {
    id: generateUniqueId,
    name: "Abiodun Olawale Solomom",
    address: "12b Emmanuel High Street Along Surface Road",
    bank: "Sterling Bank PLC",
    createdAt: "A Day Ago",
    status: "Unassigned",
  },
  {
    id: generateUniqueId,
    name: "John Obinna",
    address: "1c Timothy road, off isolo way",
    bank: "Eco Bank PLC",
    createdAt: "1 Week Ago",
    status: "Completed",
  },
  {
    id: generateUniqueId,
    name: "Chukwudi Joshua",
    address: "34 off lekki phase one, tension road",
    bank: "First Bank PLC",
    createdAt: "2 week Ago",
    status: "Assigned",
  },
  {
    id: generateUniqueId,
    name: "Abiodun Olawale Solomom",
    address: "12b Emmanuel High Street Along Surface Road",
    bank: "Sterling Bank PLC",
    createdAt: "A Day Ago",
    status: "Unassigned",
  },
  {
    id: generateUniqueId,
    name: "John Obinna",
    address: "1c Timothy road, off isolo way",
    bank: "Eco Bank PLC",
    createdAt: "1 Week Ago",
    status: "Completed",
  },
  {
    id: generateUniqueId,
    name: "Chukwudi Joshua",
    address: "34 off lekki phase one, tension road",
    bank: "First Bank PLC",
    createdAt: "2 week Ago",
    status: "Assigned",
  },
  {
    id: generateUniqueId,
    name: "John Obinna",
    address: "1c Timothy road, off isolo way",
    bank: "Eco Bank PLC",
    createdAt: "1 Week Ago",
    status: "Completed",
  },
  {
    id: generateUniqueId,
    name: "Abiodun Olawale Solomom",
    address: "12b Emmanuel High Street Along Surface Road",
    bank: "Sterling Bank PLC",
    createdAt: "A Day Ago",
    status: "Unassigned",
  },
  {
    id: generateUniqueId,
    name: "John Obinna",
    address: "1c Timothy road, off isolo way",
    bank: "Eco Bank PLC",
    createdAt: "1 Week Ago",
    status: "Completed",
  },
];
